// registration/ signup
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Jhony",
    "email": "onysmogmail.com",
    "password": "jhonny is dumb"
}

###
// login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "jonysmogmail.com",
    "password": "jhonny is dumb"
}

###
GET http://localhost:3000/api/getProduct/67801db5ea37d52b20dc91c0
###
// get authenticated users
GET http://localhost:3000/api/user

###
// Logout users
get http://localhost:3000/api/logout


###
// authentication check
GET http://localhost:3000/api/auth-check
###
// add product
post http://localhost:3000/api/addProduct
Content-Type: application/json

{
    "name": "car",
    "description": "moves abunch",
    "catagory": "vechicle",
    "price": "40000",
    "quantityInStock": "12",
    "imageURL": "image123",
    "supplierId": "11"
}

###
// update product
Put http://localhost:3000/api/updateProduct/677e62a11b5866e2c8cf3027
Content-Type: application/json

{
     "name": "banananana",
    "description": "muchas gracias",
    "catagory": "vechicle4000",
    "price": "909090",
    "quantityInStock": "12",
    "imageURL": "image1234",
    "supplierId": "11"
}
###
// get all the products
get http://localhost:3000/api/getProducts

###
// delete product
delete http://localhost:3000/api/deleteProduct